print("Wat is uw naam?")
naam = input()
print("Hallo " + naam + " Wat is uw Woonplaats?" )
woonplaats = input()
print("Bedankt, Wat is uw adres?")
adres = input()
print("Bedankt, Wat is uw postcode?")
postcode = input()

print("Naam: " + naam)
print("Adres " + adres)
print("Postcode: " + postcode)
print("Woonplaats " + woonplaats)
